# Autopirate Recipe
# ${configs_folder}/autopirate/autopirate.yml
version: "3.4"

services:
  app:
    image: jgeusebroek/privatebin
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ${appdata_folder}/privatebin/data:/privatebin/data
      - ${appdata_folder}/privatebin/config:/privatebin/cfg   
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"         
        - "traefik.http.routers.paste.entrypoints=https"
        - "traefik.http.routers.paste.rule=Host(`whoami.${var_domain}`)"
        - "traefik.http.routers.paste.tls.certresolver=${var_certresolver}"
        - "traefik.http.services.paste.loadbalancer.server.port=80"         
        - "traefik.http.routers.paste.middlewares=forward-auth@file"         

networks:
  traefik_public:
    external: true
