# Traefik Dynamic Configuration
# Middleware: Compression
# Host Path: ${configs_folder}/traefik/dynamic/compress.yaml
# Internal Path: /etc/traefik/dynamic/compress.yaml

http:
  middlewares:
    compress:
      compress: {}