# Traefik Dynamic Configuration
# Middleware: Forward Auth
# Host Path: /share/swarm/appdata/config/traefik/dynamic/forward-auth.yaml
# Internal Path: /etc/traefik/dynamic/forward-auth.yaml

http:
  middlewares:
    forward-auth:
      forwardAuth:
        address: "http://MY.NAS.LAN.IP:8080/authorize"
        trustForwardHeader: true
        authResponseHeaders:
          - X-FORWARDAUTH-NAME
          - X-FORWARDAUTH-SUB
          - X-FORWARDAUTH-EMAIL
