# Traefik Dynamic Configuration
# Routers: Static (Non-Docker) Routers
# Host Path: /share/swarm/configs/traefik/dynamic/static-routers.yaml
# Internal Path: /etc/traefik/dynamic/static-routers.yaml

http:
  routers:
    mynasname:
      entryPoints:
        - https
      middlewares:
        - forward-auth
      service: mynasname
      rule: "Host(`mynasname.MYDOMAIN.TLD`)"
      tls:
        certResolver: cloudflare
        domains:
          - main: "*.MYDOMAIN.TLD"
            sans:
              - MYDOMAIN.TLD
