# Traefik Dynamic Configuration
# Services: Static (Non-Docker) Services
# Host Path: /share/swarm/appdata/config/traefik/dynamic/static-servers.yaml
# Internal Path: /etc/traefik/dynamic/static-servers.yaml

http:
  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1"

    mynasname:
      loadBalancer:
        servers:
          - url: "https://MY.NAS.LAN.IP:8443"
