# Graylog Recipe
# /share/swarm/configs/graylog/graylog.yml
version: "3.4"

secrets:
  graylog_password:
    file: "/share/swarm/secrets/graylog_password.secret"
  graylog_password_sha2:
    file: "/share/swarm/secrets/graylog_password_sha2.secret"
  
services:
  app:
    image: graylog/graylog:3.1
    secrets:
      - graylog_password
      - graylog_password_sha2
    volumes:
# chown both folders below to PID 1100 and GID 100 or you get an error that graylog can't chown the folder to work properly
      - /share/swarm/appdata/graylog/journal:/usr/share/graylog/data/journal
      - /share/swarm/appdata/graylog/config:/etc/graylog/server
    environment:
      #CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=/run/secrets/graylog_password
      #Make next field the SHA2 HASH of the password in the previous line above:
      - GRAYLOG_ROOT_PASSWORD_SHA2=/run/secrets/graylog_password_sha2
      - GRAYLOG_WEB_ENDPOINT_URI=https://graylog.MYDOMAIN.TLD
      - GRAYLOG_REST_ENDPOINT_URI=https://graylog.MYDOMAIN.TLD/api
      - GRAYLOG_MONGODB_URI=mongodb://mongo/graylog
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - GRAYLOG_HTTP_EXTERNAL_URI=https://graylog.MYDOMAIN.TLD/
      - ROOT_TIMEZONE=America/Chicago
      - XPACK.SECURITY.ENABLED=false
      - "ES_JAVA_OPTS=-Xms512m -Xmcx512m"
    #env_file: /share/swarm/configs/graylog/graylog.env
    networks:
      - internal
      - traefik_public
    ports:
      # Graylog web interface and REST API, 9000 conflicts with Portainer default
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    deploy:
      resources:
        limits:
          # This has to be _more_ than 512MB, else Graylog will die in a ball of OOM errors
          memory: 2048M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.graylog.entrypoints=https"
        - "traefik.http.routers.graylog.rule=Host(`graylog.MYDOMAIN.TLD`)"
        - "traefik.http.routers.graylog.middlewares=forward-auth@file"
        - "traefik.http.routers.graylog.tls.certresolver=MYCERTRESOLVER"
        - "traefik.http.services.graylog.loadbalancer.server.Port=9000"  
# only necessary if your docker host DNS suffix points to a domain with a wildcard A record (graylog tries to lookup "elasticsearch.<yourdomain>", instead of using docker service discovery)
    dns_search: MYDOMAIN.TLD
    
  mongodb:
    image: mongo:4.0
    volumes:
      - /share/swarm/runtime/graylog/db:/data/db
    networks:
      - internal

# forElastic search to work properly, use this command in CLI: "sysctl -w vm.max_map_count=262144"
  es:
    image: elasticsearch:6.8.3
    ports:
      - 9200:9200
    # Elasticsearch needs the below command run via CLI to properly.
    #entrypoint: |
      #sysctl -w vm.max_map_count=262144
    volumes:
      - /share/swarm/runtime/graylog/es_data:/usr/share/elasticsearch/data
    networks:
      - internal
    environment:
      - HTTP.HOST=0.0.0.0
      - NETWORK.HOST=0.0.0.0
      - TRANSPORT.HOST=localhost
      # These will be inherited from the Graylog settings above.
      #- XPACK.SECURITY.ENABLED=false
      #- "ES_JAVA_OPTS=-Xms512m -Xmcx512m"
    #env_file: /share/swarm/configs/graylog/graylog.env
    deploy:
      resources:
        limits:
           # This has to be _more_ than 512MB, else Elasticsearch will die in a ball of OOM errors
          memory: 2048M
        reservations:
           # This has to be _more_ than 512MB, else Elasticsearch will die in a ball of OOM errors
          memory: 1024M

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.58.0/24
