# DDClient Recipe
# ${configs_folder}/ddclient/cddclient.yml
version: "3.4"

services:
  ddclient:
    image: linuxserver/ddclient:latest
    environment:
      - PUID=${var_usr}
      - PGID=${var_grp}
      - TZ=${var_tz_region}/${var_tz_city}
    volumes:
      - ${appdata_folder}/ddclient/config:/config
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ddclient.entrypoints=https"
        - "traefik.http.routers.ddclient.rule=Host(`ddclient.${var_domain}`)"
        - "traefik.http.routers.ddclient.tls.certresolver=${var_certresolver}"
        - "traefik.http.routers.ddclient.middlewares=forward-auth@file"
        - "traefik.http.services.ddclient.loadbalancer.server.port=${port_ddclient_lb}" 

networks:
  traefik_public:
    external: true
