# BitWarden Recipe
# /share/swarm/configs/bitwarden/bitwarden.yml
version: "3.4"

services:
  app:
    image: mprasil/bitwarden:latest
    environment:
      - DOMAIN='https://bitwarden.MYDOMAIN.TLD/'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/swarm/appdata/bitwarden/data:/data:rw
    networks:
        - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bitwarden.entrypoints=https"
        - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.MYDOMAIN.TLD`)"
        - "traefik.http.routers.bitwarden.tls.certresolver=MYCERTRESOLVER"
        - "traefik.http.routers.bitwarden.middlewares=forward-auth@file"
        - "traefik.http.services.bitwarden.loadbalancer.server.port=80"

networks:
  traefik_public:
    external: true
