# ouroboros Recipe
# /share/swarm/appdata/config/ouroboros/ouroboros.yml
version: "3.4"

services:
  ouroboros:
    image: pyouroboros/ouroboros:latest
    environment:
      - CLEANUP=true
      #- INTERVAL=300
      # 5 minutes is way too short an interval, daily is adequate
      - INTERVAL=86400
      #- SELF_UPDATE=true
      - TZ=America/Chicago
      - LABEL_ENABLE=true
      #- NOTIFIERS="mailtos://ouroboros@mail.MYDOMAIN.TLD:0ur0b0r0$PWD?to=myusername@gmail.com"
      - SWARM=true
      - SKIP_STARTUP_NOTIFICATIONS=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
   networks:
     - internal
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.68.0/24
