# Nextcloud Recipe
# /share/swarm/configs/nextcloud/nextcloud.yml
version: "3.4"

secrets:
  nextcloud_admin_user:
    file: "/share/swarm/secrets/nextcloud_admin_user.secret"
  nextcloud_admin_pass:
    file: "/share/swarm/secrets/nextcloud_admin_pass.secret"
  nextcloud_db_user:
    file: "/share/swarm/secrets/nextcloud_db_user.secret"
  nextcloud_db_pass:
    file: "/share/swarm/secrets/nextcloud_db_pass.secret"
  nextcloud_db_root:
    file: "/share/swarm/secrets/nextcloud_db_root.secret"

services:
  app:
    image: nextcloud:latest
    secrets:
      - nextcloud_admin_user
      - nextcloud_admin_pass
      - nextcloud_db_user
      - nextcloud_db_pass
    environment:
      - NEXTCLOUD_ADMIN_USER=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_ADMIN_PASSWORD=/run/secrets/nextcloud_admin_pass
      - NEXTCLOUD_TRUSTED_DOMAINS=MYDOMAIN.TLD
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=/run/secrets/nextcloud_db_user
      - MYSQL_PASSWORD=/run/secrets/nextcloud_db_pass
      - REDIS_HOST=redis
      - REDIS_HOST_PORT:6379    
    ports:
      - 11245:80
    volumes:
      - /share/swarm/appdata/nextcloud:/var/www/html
      - /share/swarm/appdata/nextcloud/apps:/var/www/html/custom_apps
      - /share/swarm/appdata/nextcloud/config:/var/www/html/config
      - /share/swarm/appdata/nextcloud/data:/var/www/html/data 
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nextcloud.entrypoints=https"
        - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.MYDOMAIN.TLD`)"
        - "traefik.http.routers.nextcloud.tls.certresolver=MYCERTRESOLVER"
        - "traefik.http.services.nextcloud.loadbalancer.server.port=80"     

  adminer: 
    image: adminer:latest
    networks: 
      - internal
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nextadmin.entrypoints=https"
        - "traefik.http.routers.nextadmin.rule=Host(`nextadmin.MYDOMAIN.TLD`)"
        - "traefik.http.routers.nextadmin.tls.certresolver=MYCERTRESOLVER"
        - "traefik.http.routers.nextadmin.middlewares=basic-auth@file"
        - "traefik.http.services.nextadmin.loadbalancer.server.port=8080"    

  db:
    image: mariadb:10
    secrets:
      - nextcloud_db_user
      - nextcloud_db_pass
      - nextcloud_db_root
    environment:
      # For database backup (keep 7 days daily backups)
      - MYSQL_ROOT_PASSWORD=/run/secrets/nextcloud_db_root
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=/run/secrets/nextcloud_db_user
      - MYSQL_PASSWORD=/run/secrets/nextcloud_db_pass   
    volumes:
      - /share/swarm/runtime/nextcloud/db:/var/lib/mysql
    networks:
      - internal  

  db-backup:
    image: mariadb:10
    secrets:
      - nextcloud_db_user
      - nextcloud_db_pass
      - nextcloud_db_root
    environment:
      # For database backup (keep 7 days daily backups)
      - MYSQL_PWD=/run/secrets/nextcloud_db_root
      - MYSQL_USER=/run/secrets/nextcloud_db_user
      - BACKUP_NUM_KEEP=7
      - BACKUP_FREQUENCY=1d
    volumes:
      - /share/swarm/appdata/nextcloud/database-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        mysqldump -h db --all-databases | gzip -c > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.sql.gz
        (ls -t /dump/dump*.sql.gz|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.sql.gz)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    networks:
      - internal   

  redis:
    image: redis:alpine
    volumes:
      - /share/swarm/runtime/nextcloud/redis:/data
    networks:
      - internal   

  solr:
    image: solr:6-alpine   
    volumes:
      - /share/swarm/runtime/nextcloud/solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - nextant
    networks:
      - internal      

  cron:
    image: nextcloud:latest     
    volumes:
      - /share/swarm/appdata/nextcloud:/var/www/html
    user: www-data
    entrypoint: |
      bash -c 'bash -s <<EOF
        trap "break;exit" SIGHUP SIGINT SIGTERM
        while [ ! -f /var/www/html/config/config.php ]; do
          sleep 1
        done
        while true; do
          php -f /var/www/html/cron.php
          sleep 15m
        done
      EOF'
    networks:
      - internal    

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.12.0/24
