# Traefik Dynamic Configuration
# TLS Configuration
# Host Path: /share/appdata/config/traefik/dynamic/tls-options.yaml
# Internal Path: /etc/traefik/dynamic/tls-options.yaml

tls:
  options:
    default:
      minVersion: VersionTLS12
    mintls13:
      minVersion: VersionTLS13
