# Ghost Recipe
# /share/swarm/configs/ghost/ghost.yml
version: "3.4"

secrets:
  email_for_logs:
    file: "/share/swarm/secrets/email_for_logs.secret"
  email_password:
    file: "/share/swarm/secrets/email_password.secret"

services:
  app:
    image: ghost:alpine
    secrets:
      - email_for_logs
      - email_password
    volumes:
      - /share/swarm/appdata/ghost:/var/lib/ghost/content
    environment:
      - url=https://blog.MYDOMAIN.TLD
      - NODE_ENV=production
      - mail__transport=SMTP
      - mail__options__service=Mailgun
      - mail__options__auth__user=/run/secrets/email_for_logs
      - mail__options__auth__pass=/run/secrets/email_password
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ghost.entrypoints=https"
        - "traefik.http.routers.ghost.rule=Host(`blog.MYDOMAIN.TLD`)"
        - "traefik.http.routers.ghost.tls.certresolver=MYCERTRESOLVER"
        - "traefik.http.services.ghost.loadbalancer.server.port=2368"

networks:
  traefik_public:
    external: true
