# Ghost Recipe
# ${configs_folder}/ghost/ghost.yml
version: "3.4"

secrets:
  ghost_mail_pwd:
    file: "${secrets_folder}/ghost_mail_pwd.secret"

services:
  ghost:
    image: ghost:alpine
    volumes:
      - ${appdata_folder}/ghost:/var/lib/ghost/content
    secrets:
      - ghost_mail_pwd
    environment:
      - url=https://blog.${var_domain}
      - NODE_ENV=production
      - mail__transport=SMTP
      - mail__options__service=Mailgun
      - mail__options__auth__user=${var_ghost_email}
      - mail__options__auth__pass=/run/secrets/ghost_mail_pwd
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ghost.entrypoints=https"
        - "traefik.http.routers.ghost.rule=Host(`blog.${var_domain}`)"
        - "traefik.http.routers.ghost.tls.certresolver=${var_certresolver}"
        - "traefik.http.services.ghost.loadbalancer.server.port=${port_ghost}"

networks:
  traefik_public:
    external: true
