# Dozzle Recipe
# ${configs_folder}/dozzle/dozzle.yml
version: "3.4"

services:
  app:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dozzle.entrypoints=https"
        - "traefik.http.routers.dozzle.rule=Host(`dozzle.${var_domain}`)"
        - "traefik.http.routers.dozzle.tls.certresolver=${var_certresolver}"
        - "traefik.http.routers.dozzle.middlewares=forward-auth@file"
        - "traefik.http.services.dozzle.loadbalancer.server.port=${port_dozzle_lb}"

networks:
  traefik_public:
    external: true
